import { renderFile } from "ejs";
import path from "path";
import { format } from "prettier";
import { describe, expect, it } from "vitest";
import { helpers } from "./helpers";

/**
 * Renders the connection helper template (the same way `createTemplate`
 * does) and snapshots the result. The snapshot pins the literal shape
 * the template emits for the value-bag of each input: a union of the
 * visibility-only bag and the `(value | configVar) & visibility` bag.
 * Any change to that emitted shape shows up as a diff here.
 */

const TEMPLATE_PATH = path.join(__dirname, "templates", "connections", "connection.ts.ejs");

const renderConnectionHelper = async (
  connection: {
    typeInterface: string;
    import: string;
    key: string;
    label: string;
    comments: string;
    inputs: {
      key: string;
      label: string;
      inputType: string;
      valueType: string;
      docBlock: string;
      required: boolean;
      default: undefined;
    }[];
    onPremAvailable: boolean;
    componentKey: string;
    componentIsPublic: boolean;
  },
  imports: { imports: unknown[] },
) => {
  const rendered = await renderFile(TEMPLATE_PATH, {
    connection,
    imports,
    helpers,
  });
  return format(rendered, { parser: "typescript" });
};

describe("connection helper template", () => {
  it("emits a value-bag union that allows visibility-only for every input", async () => {
    const output = await renderConnectionHelper(
      {
        typeInterface: "SlackOauth",
        import: "slackOauth",
        key: "slackOauth",
        label: "Slack OAuth",
        comments: "",
        inputs: [
          {
            key: "clientId",
            label: "Client ID",
            inputType: "string",
            valueType: "string",
            docBlock: "",
            required: true,
            default: undefined,
          },
          {
            key: "authorizeUrl",
            label: "Authorize URL",
            inputType: "string",
            valueType: "string",
            docBlock: "",
            // `getInputs` flips `required` to false when a default is
            // present, so this exercises the "input has a default"
            // branch from the integration author's perspective.
            required: false,
            default: undefined,
          },
        ],
        onPremAvailable: false,
        componentKey: "slack",
        componentIsPublic: true,
      },
      { imports: [] },
    );

    expect(output).toMatchInlineSnapshot(`
      "/**
       * This file was automatically generated by spectral.
       * Any changes made will be overwritten.
       */
      import { connectionConfigVar } from "@prismatic-io/spectral/dist/integration";
      import {
        findUserDefinedComponentKey,
        requireIntegrationContext,
      } from "@prismatic-io/spectral/dist/serverTypes";
      import type {} from "imports";

      export interface SlackOauthValues {
        clientId: string;
        authorizeUrl?: string;
      }

      /**
       * Slack OAuth
       *
       * @comments
       * This object is used to support type hinting.
       */
      export const slackOauth = {
        key: "slackOauth",
        perform: (_values: SlackOauthValues): Promise<void> => Promise.resolve(),
        inputs: {
          clientId: {
            inputType: "string",
            collection: undefined,
            default: undefined,
            required: true,
          },
          authorizeUrl: {
            inputType: "string",
            collection: undefined,
            default: undefined,
          },
        },
      } as const;

      /**
       * Slack OAuth Connection Helper
       *
       * @comments This wrapper function can be used directly in config wizard definitions.
       */
      export const slackSlackOauth = (
        stableKey: string,
        values: {
          clientId:
            | ((
                | {
                    value: string;
                  }
                | ConfigVarExpression
              ) &
                ConfigVarVisibility & { writeOnly?: true })
            | (ConfigVarVisibility & { writeOnly?: true });
          authorizeUrl?:
            | ((
                | {
                    value: string;
                  }
                | ConfigVarExpression
              ) &
                ConfigVarVisibility & { writeOnly?: true })
            | (ConfigVarVisibility & { writeOnly?: true });
        },
      ) => {
        return connectionConfigVar({
          dataType: "connection",
          stableKey,
          connection: {
            get component() {
              const context = requireIntegrationContext();
              return findUserDefinedComponentKey(
                "slack",
                true,
                context.componentRegistry,
              );
            },
            key: "slackOauth",
            values,
          },
        });
      };
      "
    `);
  });
});
